[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.texlab.config.texlab.build]
executable = "tectonic"
args = ["-X", "compile", "%f", "--synctex", "--keep-logs", "--keep-intermediates"]

[[language]]
name = "latex"
auto-format = true
formatter = { command = "tex-fmt", args = ["--stdin"] }

[[language]]
name = "markdown"
soft-wrap.enable = true

[[language]]
name = "python"
auto-format = false
language-servers = ["ruff"]

[[language]]
name = "sql"
file-types = ["sql", "sql.j2", "ddl", "dml"]
scope = "source.sql"
